# Generated by Django 5.0.7 on 2024-07-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='persona_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
