# Generated by Django 5.0.7 on 2024-07-23 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0002_persona_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona_model',
            old_name='edad',
            new_name='edad_nominal',
        ),
    ]
